import numpy as np
import cv2 as cv
from matplotlib import pyplot as plt
img1 = cv.imread('image/gel1/lane1/band1.png')
img2 = cv.imread('image/gel1/lane1/band2.png')
img3 = cv.imread('image/gel1/lane1/band3.png')
img4 = cv.imread('image/gel1/lane1/band4.png')
img5 = cv.imread('image/gel1/lane1/band5.png')
img6 = cv.imread('image/gel1/lane1/band6.png')
plt.subplot(161),plt.imshow(img1),plt.title('band1')
plt.xticks([]), plt.yticks([])
plt.subplot(162),plt.imshow(img2),plt.title('band2')
plt.xticks([]), plt.yticks([])
plt.subplot(163),plt.imshow(img3),plt.title('band3')
plt.xticks([]), plt.yticks([])
plt.subplot(164),plt.imshow(img4),plt.title('band4')
plt.xticks([]), plt.yticks([])
plt.subplot(165),plt.imshow(img5),plt.title('band5')
plt.xticks([]), plt.yticks([])
plt.subplot(166),plt.imshow(img6),plt.title('band6')
plt.xticks([]), plt.yticks([])
plt.show()
# kernel = np.ones((5,5),np.float32)/25
# dst = cv.filter2D(img,-1,kernel)
# plt.subplot(121),plt.imshow(img),plt.title('Original')
# plt.xticks([]), plt.yticks([])
# plt.subplot(122),plt.imshow(dst),plt.title('Averaging')
# plt.xticks([]), plt.yticks([])
# plt.show()
